// ==================================================
// Auto-generated file. DO NOT EDIT.
// Created: 10/20/2023, 4:44:53 PM
// ==================================================

export const jobTitles = [
  "Developer",
  "Web Developer",
  "Senior Web Developer",
  "Lead Web Developer",
  "Frontend Developer",
  "Senior Frontend Developer",
  "Lead Frontend Developer",
  "Frontend Engineer",
  "Senior Frontend Engineer",
  "Lead Frontend Engineer",
  "Front-end Developer",
  "Senior Front-end Developer",
  "Lead Front-end Developer",
  "Front-end Engineer",
  "Senior Front-end Engineer",
  "Lead Front-end Engineer",
  "Front End Developer",
  "Senior Front End Developer",
  "Lead Front End Developer",
  "Front End Engineer",
  "Senior Front End Engineer",
  "Lead Front End Engineer",
  "JavaScript Developer",
  "Senior JavaScript Developer",
  "JavaScript Engineer",
  "Senior JavaScript Engineer",
  "Full-stack Developer",
  "Senior Full-stack Developer",
  "Full-stack Engineer",
  "Senior Full-stack Engineer",
  "Full Stack Developer",
  "Senior Full Stack Developer",
  "Full Stack Engineer",
  "Senior Full Stack Engineer"
] as const;

export const baseKeywords = [
  "JavaScript",
  "TypeScript",
  "ES6+",
  "React",
  "React.js",
  "ReactJS",
  "SolidJS",
  "Solid JS",
  "Redux",
  "Zustand",
  "JSX",
  "HTML",
  "HTML5",
  "HTML 5",
  "Semantic HTML",
  "CSS",
  "CSS3",
  "CSS 3",
  "Modern CSS",
  "SASS",
  "SCSS",
  "CSS Modules",
  "Tailwind CSS",
  "CSS-in-JS",
  "Git",
  "GitHub",
  "Jest",
  "Shell Scripting",
  "Bash Scripting",
  "CLI Scripting",
  "NodeJS Scripting",
  "Ruby scripting",
  "Turborepo",
  "Turbo",
  "monorepo",
  "XML",
  "YAML"
] as const;

